source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NUAnimationKit_Example', :exclusive => true do
  pod "NUAnimationKit", :path => "../"
end

target 'NUAnimationKit_Tests', :exclusive => true do
  pod "NUAnimationKit", :path => "../"

  
end
