source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NUAnimationKit_Example' do

    pod "NUAnimationKit", :path => "../"
    pod "Masonry"

    target 'NUAnimationKit_Tests' do
        inherit! :search_paths
        pod "OCMock"
    end
end
